### ISSUE TITLE
학생출결 헤더 변경

### ISSUE THREAD

**Issue by dbwjd323** [ITA-OneByte/OneByte-FE#49]
## 📌 요약
학생출결 페이지에 헤더부분을 추가한다

## 📌 ToDo
- [x] 출결 헤더 생성하기
- [x] 통계 헤더 생성하기
- [x] 메세지함 헤더 생성하

## 🤔 ETC[선택]
