### ISSUE TITLE
성적관리 API 연결

### ISSUE THREAD

**Issue by shhyunn** [ITA-OneByte/OneByte-FE#73]
## 📌 요약
- 성적관리 API 연결

## 📌 ToDo
- [x] 성적 메인 목록 API
- [x] 성적 등록 API
- [x] 성적 상세 API
- [x] 성적 수정 API

## 🤔 ETC[선택]
